name: SNYK

on:
  workflow_dispatch:  # allow manual runs from UI
  schedule:
    - cron: "0 0 * * 0"  # weekly scan (every Sunday at 00:00 UTC)

jobs:
  scan-iac:
    name: Scan Rendered Templates (${{ matrix.chartConfig.name }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        chartConfig:
          - name: "backstage"
            path: "backstage"
          - name: "orchestrator-infra"
            path: "orchestrator-infra"
          - name: "backstage-orchestrator"
            path: "backstage"
            cliArgs: "--set orchestrator.enabled=true"

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5.0.1
        with:
          version: v4.2.3

      - name: Render Templates for ${{ matrix.chartConfig.name }}
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

          helm dependency build ./charts/${{ matrix.chartConfig.path }}
          helm template ./charts/${{ matrix.chartConfig.path }} \
            ${{ matrix.chartConfig.cliArgs || '' }} \
            --output-dir ./output/${{ matrix.chartConfig.name }}

      - name: Run Snyk IaC Scan for ${{ matrix.chartConfig.name }}
        continue-on-error: true
        uses: snyk/actions/iac@9adf32b1121593767fc3c057af55b55db032dc04 # v1.0.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          SNYK_ORG_ID: ${{ secrets.SNYK_ORG_ID }}
        with:
          args: --report --org=$SNYK_ORG_ID --target-name="redhat-developer/rhdh-chart/${{ matrix.chartConfig.name }}"
          file: ./output/${{ matrix.chartConfig.name }}
